### ISSUE TITLE
.exe not working.

### ISSUE THREAD

**Issue by Nyegnav** [Z1ni/XGP-save-extractor#10]
Xbox Game Pass for PC savefile extractor
========================================
Installed supported games:
- Starfield
Traceback (most recent call last):
  File "main.py", line 275, in <module>
  File "main.py", line 251, in main
  File "main.py", line 99, in read_containers
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MYUSERNAME\\AppData\\Local\\Packages\\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\\SystemAppData\\wgs\\0009000002294BA5_0000000000000000000000007BF72399\\47F5CA8E093541149F44E7470EF3C1AA\\container.1'
[22004] Failed to execute script 'main' due to unhandled exception!

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.

**Comment by Z1ni** [comment]
Can you create a zip of the wgs directory contents under the `C:\Users\MYUSERNAME\AppData\Local\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs` path and share it here, so I can look into this?

**Comment by SindreDenby** [comment]
Created a fork that seemingly fixed the problem, just skips the file if not found, thou may cause errors with other games.

**Comment by nemrod85** [comment]
Hi, the latest exe file fix the same problem i had like Nyegnav, zip file is generated with savegame files(.sfs). Don't know if it'll work on steam version, will check this. Thanks for your hard work Bro !

**Comment by Z1ni** [comment]
The [newest release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-09-14) contains checks and warnings for missing files and allows you to skip those (be warned, that might produce broken SFS files!).
