### ISSUE TITLE
Support for Arcade Paradise

### ISSUE THREAD

**Issue by madmaxm** [Z1ni/XGP-save-extractor#100]
## Game name: Arcade Paradise

 C:\Users\Username\AppData\LocalLow\Nosebleed Interactive\Arcade Paradise

## Game package name: WiredProductions.ArcadeParadise_hxzk6evwjr6sy

 https://drive.google.com/file/d/19t4m-krMKJNQ--75xrC0ASvomSx3_RnB/view?usp=drive_link

**Comment by Z1ni** [comment]
This has now been released: https://github.com/Z1ni/XGP-save-extractor/releases.
Please test it and report back if it works.

**Comment by madmaxm** [comment]
Hi, 
works like a charm.
Thank you!
