### ISSUE TITLE
Support for TUNIC

### ISSUE THREAD

**Issue by jacobhokanson** [Z1ni/XGP-save-extractor#106]
## Game package name: Finji.TUNIC_tys0ffscxatjj

[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/14089844/wgs.zip)

**Comment by jacobhokanson** [comment]
More info:

[steam.zip](https://github.com/Z1ni/XGP-save-extractor/files/14090326/steam.zip) contains

-  steam/001018044196~001018044334.tunic 
   - a file found under `%userprofile%\appdata\locallow\Andrew Shouldice\Secret Legend\SAVES`
-  tunic_oinkydoodl_2024-01-29_13_59_51/
   - resulting files from an attempt to extract my saves using 1cnf handler

The contents of my extracted SAVEDATA file are similar to what is stored in my steam .tunic files, but theres some metadata at the top as well as a bunch of other binary junk that doesn't display in text
( `001018044196~001018044334.tunic` on left , `SAVEDATA` from XGP-save-extractor on right)
![image](https://github.com/Z1ni/XGP-save-extractor/assets/43422884/e8a4e01c-6d25-4b15-aff8-d52db0e642e3)

Heres the head of that SAVEDATA in hex editor
![image](https://github.com/Z1ni/XGP-save-extractor/assets/43422884/daa9a5c4-f014-43b8-a76a-cbe122ad13b8)

Also, my save file is mostly complete, so the SAVEDATA generated is ~13k lines

**Comment by jacobhokanson** [comment]
ALSO I don't know why I didn't try this first, but I copied the save from wgs/xxxx/xxxx to `%userprofile%\appdata\locallow\Andrew Shouldice\Secret Legend\SAVES` and renamed it to `001018044196~001018044334.tunic` (replacing the starter save I created). 

I'm able to load up the save but it sort of seems like it combined my original save with a special puzzle save that gets created for you after reaching a certain point in the game (most things seem correct except playtime)

File 1 is the starter file, steam cloud sync put it back
File 2 is my gamepass file but it shouldn't have max playtime or that gold icon
![image](https://github.com/Z1ni/XGP-save-extractor/assets/43422884/44834ffd-9a00-40bb-8ab9-5064d6f4d5b3)

Here is what a normal save and the special save normally look like:
![image](https://github.com/Z1ni/XGP-save-extractor/assets/43422884/8524fde1-33ce-4a32-977b-3af782802bff)

**Comment by Z1ni** [comment]
I just saw the same save format for Death's Door, which seems to use serialized .NET classes, like Tunic here. See #79.
It seems that like in Death's Door, the Steam version uses separate files whereas the Game Pass version uses serialized .NET lists that contain the data for multiple files.

It's maybe possible to extract the saves by parsing the serialized data, but that requires more work than just renaming files.

**Comment by Z1ni** [comment]
Maybe some Googling would find the save system the games use? As the structure and class names are so similar/identical, I'm guessing that these are created by some Unity plugin etc. I did some quick searching by the class names, but didn't find anything (but I spent maybe a minute or two, so your mileage may vary).
