### ISSUE TITLE
Support for XPG Starfield V1.9.51.0

### ISSUE THREAD

**Issue by Howard-Starfield** [Z1ni/XGP-save-extractor#110]
## Game name: Starfield 
![Screenshot_1980](https://github.com/Z1ni/XGP-save-extractor/assets/158320445/a5eac650-3cdb-4aa9-8044-480e78ca179e)
After the recent patch, we can no longer extract/convert XGP Starfield from xbox pc version to play on the Steam version.
My Wgs is too big to upload =(

**Comment by Z1ni** [comment]
Yeah, GitHub doesn't like larger files, but you can upload the wgs zip to Google Drive, Microsoft OneDrive, Dropbox, Mega, etc.

**Comment by Howard-Starfield** [comment]
Tha

> Yeah, GitHub doesn't like larger files, but you can upload the wgs zip to Google Drive, Microsoft OneDrive, Dropbox, Mega, etc.

Thank you for this quick reply! The link is my WGS file, hope this helps =)
[https://drive.google.com/file/d/1xFFyRIdahFaw4U_onxnThMZ-3RPtkoxk/view?usp=sharing](url)

**Comment by Dsheppp** [comment]
Hey Z1ni im a little confused on what to do after zipping the wgs file? the extractor is still failing

**Comment by Z1ni** [comment]
> Hey Z1ni im a little confused on what to do after zipping the wgs file? the extractor is still failing

The zipped wgs is just used by me to add support for games. If you could also upload it to somewhere and link it here, I'd appreciate that. It'll help diagnosing the issue and fixing it.

As said above, you can upload it to Google Drive, Microsoft OneDrive, Dropbox, Mega, or wherever you want as long as you can share it with me (here or by email [check my profile]).

**Comment by Z1ni** [comment]
@Howard-Starfield @Dsheppp Can you try this version and report back here if it can extract the saves and if the saves work with the Steam version?

[xgp-save-extractor_starfield_new_format.zip](https://github.com/Z1ni/XGP-save-extractor/files/14127871/xgp-save-extractor_starfield_new_format.zip)

**Comment by Howard-Starfield** [comment]
> @Howard-Starfield @Dsheppp Can you try this version and report back here if it can extract the saves and if the saves work with the Steam version?
> 
> [xgp-save-extractor_starfield_new_format.zip](https://github.com/Z1ni/XGP-save-extractor/files/14127871/xgp-save-extractor_starfield_new_format.zip)

I tried to download it from Microsoft Broswer and Google Chrome, but both of them removed the zip as soon as it downloaded.

**Comment by Howard-Starfield** [comment]
> @Howard-Starfield @Dsheppp Can you try this version and report back here if it can extract the saves and if the saves work with the Steam version?
> 
> [xgp-save-extractor_starfield_new_format.zip](https://github.com/Z1ni/XGP-save-extractor/files/14127871/xgp-save-extractor_starfield_new_format.zip)

It worked! Thank you so much for this quick fix, you are the best!!!
![image](https://github.com/Z1ni/XGP-save-extractor/assets/158320445/2a5ee861-704f-4c4c-b8e4-4f3b085a81b7)

**Comment by Z1ni** [comment]
Does the extracted save work with the Steam version?

**Comment by Howard-Starfield** [comment]
Yeah, it's working [❤️-❤️]

**Comment by Dsheppp** [comment]
I am unable to download the new file, says virus detected.

**Comment by Z1ni** [comment]
> I am unable to download the new file, says virus detected.

You could either:
- Add an exception to your virus scanner or turn it off temporarily (maybe there's an "ignore" button or something when you download the release exe?)
or
- Install [Python](https://www.python.org/downloads/) and download the [files in this repo](https://github.com/Z1ni/XGP-save-extractor/archive/refs/tags/release-2024-02-01.zip) and run the script by double-clicking the `main.py` file.

**Comment by Dsheppp** [comment]
python worked, now gaming on steam. THANK YOU!!
