### ISSUE TITLE
Cant extract Forza Horizon 5 save

### ISSUE THREAD

**Issue by SemSau** [Z1ni/XGP-save-extractor#113]
Xbox version isnt installed but the save is still in the right location
![image](https://github.com/Z1ni/XGP-save-extractor/assets/67237163/f53a303c-bb79-45ce-a4cf-8b99637483be)
![image](https://github.com/Z1ni/XGP-save-extractor/assets/67237163/c0c8661d-ffb4-43a2-8abf-4c5c1ca60cd4)

**Comment by Z1ni** [comment]
The folder that's in your screenshot should contain `containers.index`. It seemingly doesn't, so I'm assuming that when you uninstalled the game, it got removed. The saves should come back if you reinstall the game.

**Comment by SemSau** [comment]
Since i dont have game pass anymore i instead found an older save from almost 2 years ago (i havent played it in a while) that had that file, and copied that into the right directory

Now i got a permission error (could be from the backup i found, but i checked permissions and it should be fine)
![image](https://github.com/Z1ni/XGP-save-extractor/assets/67237163/c2b90b59-eb57-4acf-bee3-64b020a12e1d)

**Comment by Z1ni** [comment]
Try to run the extractor exe from a folder your user account can access, for example the Downloads folder or the Documents folder.

**Comment by SemSau** [comment]
The issue was that i forgot to paste it into the save folder
