### ISSUE TITLE
Support for Persona 3 Reload

### ISSUE THREAD

**Issue by twstkrm** [Z1ni/XGP-save-extractor#114]
## Game package name: SEGAofAmericaInc.L0cb6b3aea_s751p9cej88mt

 
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/14135496/wgs.zip)

**Comment by Z1ni** [comment]
It seems that the Steam saves are encrypted, so adding support for this seems unlikely at least for now.

**Comment by Z1ni** [comment]
You can try to load these unencrypted saves with the Steam version and maybe if we're lucky, it'll work.

These are your extracted saves:
[persona_3_reload_2535424010670539_2024-02-02_18_25_04.zip](https://github.com/Z1ni/XGP-save-extractor/files/14142706/persona_3_reload_2535424010670539_2024-02-02_18_25_04.zip)

**Comment by illusion0001** [comment]
Tested this, doesn't show up.

**Comment by Z1ni** [comment]
Shame :disappointed: 

I'll close this for now, as I can't really do anything about the encryption.

**Comment by illusion0001** [comment]
Save decrypt tool: https://github.com/illusion0001/P3R-Save-EnDecryptor

**Comment by kuro225** [comment]
> Save decrypt tool: https://github.com/illusion0001/P3R-Save-EnDecryptor

How do I use this?

**Comment by aayznn** [comment]
how do you use the extractor above? im kind of a noob to this :C

**Comment by Exiiaa** [comment]
> Save decrypt tool: https://github.com/illusion0001/P3R-Save-EnDecryptor

When I run the program, it just did nothing, any idea why?

**Comment by Lespinonsa** [comment]
Any chance you can decrypt my save files so I can move my save from gp to steam? the program is not working for me. @illusion0001. I appreciate it, thank you!
[save.zip](https://github.com/Z1ni/XGP-save-extractor/files/14314295/save.zip)

**Comment by RealDarkCraft** [comment]
if you want I know how to edit these saves (I know how to do it for steam but it can also work for other versions)

**Comment by eacj** [comment]
Hey guys! Any news on this one? 😭
