### ISSUE TITLE
Starfield missing files issue

### ISSUE THREAD

**Issue by SindreDenby** [Z1ni/XGP-save-extractor#13]
I have been checking out why I don't always get my Starfield saves when I use the script. After doing some deduction it seems that when you save in game it doesn't actually create the save file in the "...\SystemAppData\wgs\..." but somewhere else (idk where). A folder for the save file will be created instantly in the "/wgs" directory without the actual save data. Then with some Xbox "magic" the save file/data, after some delay, is moved to the "/wgs" directory in the background. My best guess is that it has something to do with cloud backup. The save files transfers are done individually and has a couple minutes delay between each of them.

Basic fix: Wait 10 to 20 minutes (depending on how many saves are pending) then run the script again. 

Should probably be a warning for the user when save data is missing that the data is still being (cloudified?) by Xbox and that the user should wait and try running the script again after a few minutes

**Comment by Z1ni** [comment]
I added some warnings about missing files when running the script. See [the newest release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-09-14) and 1e07f59.
