### ISSUE TITLE
Support for Plague Tale Requiem

### ISSUE THREAD

**Issue by pancakesbutter** [Z1ni/XGP-save-extractor#139]

**Comment by Z1ni** [comment]
This should already work, have you tested it?

**Comment by pancakesbutter** [comment]
Yes I tried and it recognized the save, but says the save was corrupted and
must be overwritten

**Comment by Z1ni** [comment]
Marking this as incompatible for now.

**Comment by GlitchedCod** [comment]
I have the same problem, does installing an older version of the game and updating it would fix the save file ? It's weird that they're different, even if they're all PC versions. Pretty sure it's just some basic json or yaml behind this save file format.
