### ISSUE TITLE
Request: support for Power Wash Simulator? 

### ISSUE THREAD

**Issue by virias** [Z1ni/XGP-save-extractor#14]
Not sure if you take them but would love if you could somehow please manage it! If you need any files or info on installation directories etc, let me know and I'll do my best to track it down.

**Comment by Z1ni** [comment]
Sure, I can look into it if you have a XGP save for it. Having a Steam version save would also help, though I could probably find one online.

Check `%LocalAppData%\Packages` for a folder name that might contain the game name and zip the `SystemAppData\wgs` folder inside it and share it here or by email (you can find my email at my GitHub profile). I'll also need the containing folder name from the Packages folder.
