### ISSUE TITLE
Support for 'High on Life'?

### ISSUE THREAD

**Issue by tkoeck** [Z1ni/XGP-save-extractor#15]
Hi,

a support for High on Life would be dope.

I can support you with XBGP and Steam save games if required.

**Comment by Z1ni** [comment]
Sure, zip up `SystemAppData\wgs` under the correct folder in `%LocalAppData%\Packages` and provide the name of the containing folder, and I'll take a look. Also the Steam save would be nice.

**Comment by tkoeck** [comment]
Here you go. Thanks for looking into it.

[High On Life.zip](https://github.com/Z1ni/XGP-save-extractor/files/12553372/High.On.Life.zip)

**Comment by Z1ni** [comment]
Done in [ad9c6ac](https://github.com/Z1ni/XGP-save-extractor/commit/ad9c6ac2a0bd5e876480411aac8a0ca06f23b12e).

Check out the [newest release](https://github.com/Z1ni/XGP-save-extractor/releases/latest).

**Comment by tkoeck** [comment]
Btw. it works on Steam. Just tried it. Thanks and have a nice afternoon.
