### ISSUE TITLE
Support for Manor Lords

### ISSUE THREAD

**Issue by ThSdS** [Z1ni/XGP-save-extractor#152]
## Game package name: HoodedHorse.ManorLords_znaey1dw2bdpr
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/15138474/wgs.zip)

**Comment by Z1ni** [comment]
Support for Manor Lords is now available: https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2024-07-05
