### ISSUE TITLE
Support for [Manor Lords]

### ISSUE THREAD

**Issue by TheAkeno** [Z1ni/XGP-save-extractor#154]

**Comment by TheAkeno** [comment]
Game package name: HoodedHorse.ManorLords_znaey1dw2bdpr

**Comment by DeicPro** [comment]
Duplicate of https://github.com/Z1ni/XGP-save-extractor/issues/152

**Comment by Z1ni** [comment]
Closed as duplicate of #152

**Comment by Z1ni** [comment]
Support for Manor Lords is now available: https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2024-07-05
