### ISSUE TITLE
Please Add Support for Coral island

### ISSUE THREAD

**Issue by Safimoon** [Z1ni/XGP-save-extractor#161]
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/15503232/wgs.zip)

## Game Name: Coral Island
 i would like the script to support this game as well. but also can you make a version to where Steam can also extract the save to go back to XGP? please it be much appreciated i ended up getting the XGP save from this link on to my steam version but would like to transfer back to XGP please. https://steamcommunity.com/app/1158160/discussions/0/3830919351650000359/ 
i am attaching both my personal game play Steam and XGP Saves here.

## Game package name: For XGP is \Packages\HumbleBundle.CoralIsland_q2mcdwmzx4qja\SystemAppData\wgs For Steam Saves is in ProjectCoral\Saved\SaveGames under the AppData\Local\ file section.
@Z1ni 

[SaveGames.zip](https://github.com/Z1ni/XGP-save-extractor/files/15503473/SaveGames.zip)

**Comment by Z1ni** [comment]
Thanks for the request and the files!

I converted your XGP saves, can you test that those load in game?
[coral_island_2535434060661147_2024-07-03_02_15_34.zip](https://github.com/user-attachments/files/16075112/coral_island_2535434060661147_2024-07-03_02_15_34.zip)
