### ISSUE TITLE
Support for Ark Survival Ascended single player

### ISSUE THREAD

**Issue by mstarkey9999** [Z1ni/XGP-save-extractor#165]
## Game package name: StudioWildcard.ARKSurvivalAscended_1w2mm55455e38

[SavedArksLocal.zip](https://github.com/user-attachments/files/15753268/SavedArksLocal.zip)
[wgs.zip](https://github.com/user-attachments/files/15753270/wgs.zip)

**Comment by Z1ni** [comment]
Thanks for the request and the files!

I extracted the following files from your wgs zip, can you please check if those work for your Steam version?
There's some extra files in there compared to your Steam save example and I'm not sure if those are named correctly for the Steam version, but at least the .ark and .arkprofile files are there.

[ark__survival_ascended_2533274806320753_2024-07-03_12_50_50.zip](https://github.com/user-attachments/files/16081945/ark__survival_ascended_2533274806320753_2024-07-03_12_50_50.zip)

**Comment by mstarkey9999** [comment]
I did have to change the extensions on a couple of files and place the files in the right directories, which was no big deal.  I see the save listed in my saves but when I try to launch it, it immediately crashes back to the desktop.

**Comment by mstarkey9999** [comment]
I'm starting to think you are right that there is no easy way to transfer them.  As far as changes that I made, a couple of the files had a .sav extension in the folders that I have but didn't in the zip file you posted.  I did try just copying the SavedArksLocal directory and got the same thing.

**Comment by mstarkey9999** [comment]
Thank you for your effort on this.

**Comment by Z1ni** [comment]
Shame that it didn't work.

I'm marking the game as unsupported for now.
