### ISSUE TITLE
Support for Monster Hunter Rise

### ISSUE THREAD

**Issue by Huntecher** [Z1ni/XGP-save-extractor#166]
## Game package name: F024294D.50755C2F12831_8fty0by30jkny

[wgs.zip](https://github.com/user-attachments/files/15846127/wgs.zip)

**Comment by Z1ni** [comment]
Duplicate of #86

**Comment by Z1ni** [comment]
I tried to extract your saves, can you confirm if those work?

[monster_hunter_rise_2535467671905894_2024-07-03_17_34_32.zip](https://github.com/user-attachments/files/16086520/monster_hunter_rise_2535467671905894_2024-07-03_17_34_32.zip)
