### ISSUE TITLE
Support for Callisto Protocol

### ISSUE THREAD

**Issue by Ranger125** [Z1ni/XGP-save-extractor#171]
Game name: The Callisto Protocol

Game package name: PUBGCorp.TheCallistoProtocolXB1_gsxfe54jwf950

[wgs.zip](https://github.com/user-attachments/files/16074519/wgs.zip)

**Comment by Z1ni** [comment]
Thanks for the request and the files.

I converted your saves, can you try if those work on your Steam/Epic version before I add the support to a released version?
[the_callisto_protocol_2535429441249268_2024-07-03_01_36_37.zip](https://github.com/user-attachments/files/16074913/the_callisto_protocol_2535429441249268_2024-07-03_01_36_37.zip)

**Comment by Ranger125** [comment]
Took me a while to download the game, it worked. Thanks for the quick reply.
