### ISSUE TITLE
Support for Cricket 24

### ISSUE THREAD

**Issue by Jumping-Pengin** [Z1ni/XGP-save-extractor#172]
## Game package name: BigbenInteractiveSA.Cricket24Win10_tqjv3vrxr8ppw
[wgs.zip](https://github.com/user-attachments/files/16144669/wgs.zip)
[Cricket 24.zip](https://github.com/user-attachments/files/16144674/Cricket.24.zip)

**Comment by Z1ni** [comment]
Thanks for the request!

I converted your save files. Can you please test them and report back here if they work?
[cricket_24_2535471649200151_2024-07-28_21_22_04.zip](https://github.com/user-attachments/files/16404839/cricket_24_2535471649200151_2024-07-28_21_22_04.zip)

**Comment by Jumping-Pengin** [comment]
Thanks it works.
