### ISSUE TITLE
Do You Need the Game Installed?

### ISSUE THREAD

**Issue by Gilgamang** [Z1ni/XGP-save-extractor#173]
I booted it up and this is all it says:

            Xbox Game Pass for PC savefile extractor
            ========================================
            Installed supported games:
            - Lies of P
              No containers for the game, maybe the game is not installed anymore
            
            
            Press enter to quit

I don't have GP anymore which is why I want to migrate my data. Do I need to install a game for it to work?

**Comment by Z1ni** [comment]
This save extractor reads the saves from where the Xbox app syncs the cloud saves to. If you uninstall a game, the Xbox app also removes the local saves.

I'm not sure if the Xbox app lets you reinstall games without a subscription. I've seen that the saves are not deleted when the subscription expires, only after you manually uninstall the game.

If the Xbox app doesn't allow you to reinstall the game without a subscription, then I'm afraid that the only way to get the saves would be to resubscribe and reinstall the game after that.
