### ISSUE TITLE
Support for Like a Dragon: Ishin

### ISSUE THREAD

**Issue by langiam** [Z1ni/XGP-save-extractor#180]
## Game package name:  like_a_dragon__ishin_2541316932588155

https://drive.google.com/file/d/1EGMx3ZzXv7ksqcbGtp-n9_yYEZLvYqoi/view?usp=drive_link

**Comment by Z1ni** [comment]
This game should already be supported, although it's not tested. Did you try to extract the save and test if it works?

**Comment by langiam** [comment]
I did. Unfortunately in game the saves do not work. Let me know if you need
a screen capture, but the way the data is read in game for some reason
shows only the difficulty setting and PNG image. When you try to load the
file little loading screen pops up and an error screen follows.

**Comment by langiam** [comment]
![UujNQ5SfpB](https://github.com/user-attachments/assets/0c40852a-a2bc-44cf-8cdb-e55e1c4f7840)
![LikeaDragonIshin-Win64-Shipping_indVKmf3IF](https://github.com/user-attachments/assets/fbd1c2f5-6b6a-45f9-b999-3c9b75990d01)

**Comment by Z1ni** [comment]
I looked into this a bit and unfortunately the saves are a bit different between the Steam and XGP versions, so save transfer isn't possible without more research into this, which I'm not really capable of (I don't have the game) or especially interested to do right now. Also this tool isn't really meant to do complicated save conversions, only very simple ones which don't require decryption and such.

I'm marking this game as unsupported for now, as well as other Like a Dragon games which seem to use the same format.

Thanks for the report and sorry that this didn't work.
