### ISSUE TITLE
Support for [Neon White]

### ISSUE THREAD

**Issue by PhantasM0666** [Z1ni/XGP-save-extractor#185]
## Game package name: AnnapurnaInteractive.NeonWhite_c96c51jf6wkvm

[wgs.zip](https://github.com/user-attachments/files/16567663/wgs.zip)

**Comment by snab43** [comment]
I'm currently working on this, but unfortunately the game seems to be using a custom encoding method. Probably to avoid cheating leaderboards. I can successfully get it to extract everything in the necessary format and the save file is a nice read-able JSON object, but when launching the game on Steam it doesn't recognize the save.

For anyone else reading this, where I'm at so far is adding this to games.json (at the bottom or where ever you want):

```
        {
            "name": "Neon White",
            "package": "AnnapurnaInteractive.NeonWhite_c96c51jf6wkvm",
            "handler": "neon-white"
        }
```

And adding this block on line 481 (after coral-island's handler):
```
    elif handler_name == "neon-white":
    # Each container represents one folder, and each underscore in the file name represents a subfolder
        for container in containers:
            folder_name: str = container["name"]
            for file in container["files"]:
                # Rename "prefs-windows.dat" to "prefs.dat"
                if file["name"] == "prefs-windows.dat":
                    fname = "prefs.dat"
                else:
                    # Replace underscores in the file name with slashes to create folders
                    fname = file["name"].replace("_", "/")
                zip_fname = f"{folder_name}/{fname}"
                fpath = file["path"]
                save_meta.append((zip_fname, fpath))
```

**Comment by snab43** [comment]
This game encrypts it's save files on Steam (probably to discourage cheating on the leaderboards). That encryption key would be stored in the game's code.

I'm not sure how feasible this would be as sharing it could violate some EULA. It also would allow people to cheat leaderboards.

**Comment by Z1ni** [comment]
Yeah, I'd rather not include support for decrypting encrypted game saves (this or other games).

I've been thinking if this tool should extract the files even if the format isn't what any other (Steam/Epic/etc.) game version accepts, as it would still be useful for backing up things, even if those saves couldn't be used elsewhere.

But that's not something to be decided right now. Thanks for investigating this, @snab43. I'll mark Neon White unsupported and close this issue after that.

**Comment by snab43** [comment]
For what it's worth, I (allegedly) got it working and I (allegedly) decompiled the game's code to get the encryption key. For some reason the Xbox version stores your save file in a plain text JSON object. But the Steam version can't read that, it can only read the encrypted version.

So yeah, probably best to mark this as unsupported if you want to avoid any gray areas.

Thanks, though! I found this because I wanted to move my Neon White save from Game Pass to Steam and I couldn't have done it without your code. I appreciate the project.

**Comment by 200433zc** [comment]
> For what it's worth, I (allegedly) got it working and I (allegedly) decompiled the game's code to get the encryption key. For some reason the Xbox version stores your save file in a plain text JSON object. But the Steam version can't read that, it can only read the encrypted version.无论如何，我（据称）让它正常工作，并且我（据称）反编译了游戏的代码以获取加密密钥。由于某种原因，Xbox 版本将您的保存文件存储在纯文本 JSON 对象中。但Steam版本无法读取，只能读取加密版本。
> 
> So yeah, probably best to mark this as unsupported if you want to avoid any gray areas.所以，是的，如果您想避免任何灰色区域，最好将其标记为不受支持。
> 
> Thanks, though! I found this because I wanted to move my Neon White save from Game Pass to Steam and I couldn't have done it without your code. I appreciate the project.不过谢谢！我发现这个是因为我想将我的 Neon White 保存从 Game Pass 移至 Steam，如果没有您的代码我就无法完成此操作。我很欣赏这个项目。

Can you share the conversion method, I received 3 months xgp from nvdia, I thought I had plenty of time to play but ended up not finishing it, when I think about it for the future playing I realize my save doesn't work, that's annoying isn't it 😣,
