### ISSUE TITLE
Unable to Extract save file from Starfield XGP

### ISSUE THREAD

**Issue by nite2k** [Z1ni/XGP-save-extractor#19]
can you please help?

**Comment by nite2k** [comment]
in order to use the Steam version, I'd like to move my save files out of XGP

**Comment by Z1ni** [comment]
Can you provide more details? Does the script display any errors? Is your game installed in the C: drive?

**Comment by nite2k** [comment]
I'm sorry! I totally missed that you have a script for Starfield only. I just downloaded it and it works perfectly. Again, my apologies!
