### ISSUE TITLE
Can we use the extracted zip to restore save files if I reinstall an XBox Game Pass game?

### ISSUE THREAD

**Issue by roytang** [Z1ni/XGP-save-extractor#207]
Sorry, I couldn't find this in the readme.

**Comment by Z1ni** [comment]
Unfortunately not, the extracted saves in the zip need to be converted back to XGP format, which this tool doesn't do.

For Starfield there is [starfield-xgp-import](https://github.com/HarukaMa/starfield-xgp-import) tool, but I'm not aware of a tool that does that for all games.

**Comment by roytang** [comment]
Thanks for the quick response!

**Comment by brodrigz** [comment]
Hi, I've implemented this feature on a [dotnet port of this tool](https://github.com/brodrigz/XgpSaveTools)
It allows to replace your XGP saves with any other saves
