### ISSUE TITLE
Can't pull Saves From xbox Error. 

### ISSUE THREAD

**Issue by Clessith** [Z1ni/XGP-save-extractor#21]
Xbox Game Pass for PC savefile extractor
========================================
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    main()
  File "main.py", line 256, in main
    temp_dir = tempfile.TemporaryDirectory(ignore_cleanup_errors=True)
TypeError: __init__() got an unexpected keyword argument 'ignore_cleanup_errors'

Any help?  I keep getting "Caution! You are low on space to save your progress." errors and I want to abandon Xbox.

**Comment by Z1ni** [comment]
Your Python is too old, update it: https://www.python.org/downloads/

Alternatively you can just remove the `ignore_cleanup_errors=True` part from the indicated line, it shouldn't be absolutely necessary.
