### ISSUE TITLE
Expected one user directory in wgs directory, found 2

### ISSUE THREAD

**Issue by slightlypanda** [Z1ni/XGP-save-extractor#22]
First of all thank you for making this tool. Hopefully you can help me figure out this error. I saw someone else with a similar problem and they went about fixing it by deleting empty folders, but I think they may have just gotten lucky. I uploaded my saves to mediafire incase you wanted to take a look. Thanks for your time!
![image](https://github.com/Z1ni/XGP-save-extractor/assets/104712413/41e5e77f-adab-4a83-8aaa-fb85c1f0373e)

Save files: [https://www.mediafire.com/file/anv0szhn2gt4m70/wgs.7z/file](url)

-edit- uploaded to mediafire instead on drive

**Comment by bopna** [comment]
I get the exact same error. I did do a "steam -> game pass" and then played on Xbox on a trip. Now i want to convert those saves back to my main PC and Steam..

Would love to get some guidance.

**Comment by slightlypanda** [comment]
Tried the same thing but I just get container errors.

![image](https://github.com/Z1ni/XGP-save-extractor/assets/104712413/953dd547-faeb-48a7-9fe1-a18cfc63ef27)

Starting to suspect it may have to do with cloud save. I have no idea. I'm just poking at things while maintaining a backup while seeing what works.

**Comment by slightlypanda** [comment]
Not sure what is up with that link on drive. Reuploaded it to MediaFire: [https://www.mediafire.com/file/anv0szhn2gt4m70/wgs.7z/file](url)

**Comment by slightlypanda** [comment]
I finally got it to work. Here are my steps so author can replicate or other people with the same issues can fix. 

1. Navigated to AppData\Local\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs folder.
2. Moved the backup folder and the t folder out. Program was confused by these folders.
3. I went into the game, loaded up my latest save, and saved again to see the new folder. I deleted all other folders in wgs\000901F8470AAC65_0000000000000000000000007BF72399 folder leaving the container file.
4. Ran exe again and it worked fine.

**Comment by Z1ni** [comment]
Was the `.backup.20230908011802` folder made by you, or was it in there already?

**Comment by ya-boop** [comment]
Traceback (most recent call last):
  File "H:\ContentX\bruh\main.py", line 255, in main
    read_result = read_containers(supported_xgp_apps[name])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ContentX\bruh\main.py", line 102, in read_containers
    with open(os.path.join(container_path, f"container.{container_num}"), "rb") as cf:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\maxim\\AppData\\Local\\Packages\\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\\SystemAppData\\wgs\\000901FDEA34D8F5_0000000000000000000000007BF72399\\AD050EF141314A78A1E66AEA5FA116F9\\container.1'


same. i have this file

**Comment by slightlypanda** [comment]
> Was the `.backup.20230908011802` folder made by you, or was it in there already?

It was in there already.

**Comment by bopna** [comment]
> Was the `.backup.20230908011802` folder made by you, or was it in there already?

It was there already. 
Seems related to cloud save between PC and Xbox. If I remember correctly I could not load in my save at first if I removed the backup folder.

**Comment by Z1ni** [comment]
The newest release warns about missing files, but allows you to continue.
The missing files can be caused by incomplete cloud save syncing, but I'm not 100% sure about that. The missing files might be duplicated in the data so it might not be an issue.

Either way, the [newest release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-09-14) should extract at least some save files and skip backups.
