### ISSUE TITLE
Exe instantly closes and will only extract atomic heart, not Starfield

### ISSUE THREAD

**Issue by jpopie** [Z1ni/XGP-save-extractor#23]
Been playing starfield on the gamepass then found this, tried using the exe and the main.py file and it will only extract atomic heart, once I uninstalled atomic heart it wont extract anything. The exe also instantly closes so I cant see whats going wrong.

**Comment by tkoeck** [comment]
Why don't you use the Python file with Python on the command line? There you can see the error message, too.

**Comment by Z1ni** [comment]
Is the game installed on the C: drive?
