### ISSUE TITLE
Exe and python script open then close immediately upon running

### ISSUE THREAD

**Issue by Pink-skul** [Z1ni/XGP-save-extractor#26]
Hi there,

I started with the exe and nothing happened. The terminal opened and then closed. No zip file of any saves. Nothing.

I removed all empty gamepass saves. Same thing.

Attempted running the script in python directly, same story. Nothing.

Please can you advise if I'm doing something wrong

**Comment by Z1ni** [comment]
Did you try to run the script in the console? That way you should get at least some output.
Is the game installed on the C: drive?

**Comment by Pink-skul** [comment]
I did yes. Tried running the script and the exe in both python and cmd consoles.

No the game is installed on my second drive D:

**Comment by Pink-skul** [comment]
I moved the game over to the C: drive through the Xbox program but the same issue still occurs

**Comment by Z1ni** [comment]
Does `%LocalAppData%\Packages` contain folders that mention Bethesda and/or Starfield/"Project Gold"?

**Comment by Pink-skul** [comment]
It does yes, the following folder - ./BethesdaSoftworks.ProjectGold_3275kfvn8vcwc

**Comment by Pink-skul** [comment]
Ok so solved it. Need to make sure that are NO other files/folders in Packages/BethesdaSoftworks.ProjectGold_3275kfvn8vcwc/SystemAppData that are not the main saves folder that contains all the save folders and files.

**Comment by Z1ni** [comment]
Folders under the `SystemAppData` folder shouldn't cause problems, but currently the script assumes only one user folder in addition to the `t` folder under `wgs`. What folders did you have under `wgs`?

Multi-user support will probably be addressed in #22
