### ISSUE TITLE
Does it work on Steam deck?q

### ISSUE THREAD

**Issue by tobbeloo** [Z1ni/XGP-save-extractor#27]
Is it the same setup if I wanna move a save from Xbox cloud stream to my Steam deck if I buy the game from Steam? If not, would it be possible to ask for a special Steam deck version of XGP-save-extractor. But might not work at all..

**Comment by Z1ni** [comment]
I guess that if you play Starfield by streaming it, your local Xbox/PC doesn't have the save files, so you can't extract them.

If you have the game on PC via the Xbox app (locally, not streaming), you should be able to extract the save and then move it to the Steam Deck either through cloud saves or by moving the save files to your Deck manually.

**Comment by Z1ni** [comment]
Closing as inactive.
