### ISSUE TITLE
Request: Tinykin

### ISSUE THREAD

**Issue by B1BU** [Z1ni/XGP-save-extractor#28]
I put maybe about 10 hours into this game before they removed it from XGP and I really wish I could pick up where I left off on Steam. The XGP save data is mostly readable with a hex editor, but for some reason the Steam save data is a jumbled mess of characters.

If you could at least point me in the right direction as to how to convert the save data I'd be extremely grateful.

[Tinykin Saves.zip](https://github.com/Z1ni/XGP-save-extractor/files/12674467/Tinykin.Saves.zip)

**Comment by Z1ni** [comment]
Unfortunately the Steam save file seems to be either compressed or encrypted. Quick experimentation with zlib yielded no results.

Maybe it would be somewhat easy to reverse engineer the game to figure out the save file format, as it seems to be an Unity game.

**Comment by B1BU** [comment]
I'm really confused as to why the two saves are different, that doesn't seem to usually be the case. XGP game version was the latest one so I don't think it's a version thing. The XGP version seems to be what the unencrypted Steam version should look like. I don't know if that helps.

**Comment by Z1ni** [comment]
I'm afraid that I can't do anything else here, as I don't have the game to even try to figure out the save format. Sorry 😢
