### ISSUE TITLE
Failed to extract saves:

### ISSUE THREAD

**Issue by Kr4der** [Z1ni/XGP-save-extractor#29]
Xbox Game Pass for PC savefile extractor
========================================
Installed supported games:
- Starfield
  Failed to extract saves:
Traceback (most recent call last):
  File "main.py", line 371, in main
  File "main.py", line 335, in get_save_paths
Exception: Unsupported XGP app "BethesdaSoftworks.ProjectGold_3275kfvn8vcwc!GAME"

Press enter to quit

**Comment by Z1ni** [comment]
Fixed in 6603432.

Please try again with the newest release: https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-09-23

**Comment by Kr4der** [comment]
It Worked, thank you so much!
