### ISSUE TITLE
lies of P

### ISSUE THREAD

**Issue by f520k510** [Z1ni/XGP-save-extractor#30]
Can you make it work for lies of P?
Thanks.

**Comment by Z1ni** [comment]
Sure, I can take a look if you provide me the save files from `%LOCALAPPDATA%\Packages\Neowiz.3616725F496B_r4z3116tdh636\SystemAppData\wgs\`. Zip up the folders under that path and share the zip either here or by sending me an email (check my profile). Or use Google Drive and share the file with my email, whatever you like.

If you also have Steam saves, those would be helpful to also include in the zip, so I can check if the save file format is the same between the versions.

**Comment by Z1ni** [comment]
This should now work as of 4d9acac.

Download the newest release from https://github.com/Z1ni/XGP-save-extractor/releases/latest and report back here if it works.

**Comment by Sutsuko** [comment]
Hello.
Is it possible to transfer from Steam to Gamepass?

**Comment by f520k510** [comment]
> Hello. Is it possible to transfer from Steam to Gamepass?

Yes, I managed to do it with some manual files manipulation.
In your steam saves folder there are 5 files.
Account_1.sav
Account_2.sav
OptionSlot.sav
SaveData-1_Character_1.sav
SaveData-1_Character_2.sav

You need to start lies of p in game pass and save the game.
Then you should have a folder here:
C:\Users\yourname\AppData\Local\Packages\Neowiz.3616725F496B_r4z3116tdh636\SystemAppData\wgs\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\

Sort the xxxxxxxx folders with time descending.
Copy the steam saves files into each of the 5 folders of game pass saves, copy the numeric file's name, rename your steam save files to the numeric file name, and delete the old numeric files.

I did it several times soＩam confident it will work.
Let me know if you run into any trouble.
