### ISSUE TITLE
Request: Support Celeste

### ISSUE THREAD

**Issue by JimmyRespawn** [Z1ni/XGP-save-extractor#31]
Played this on Xbox Live Gold/PGP. Did not finish it. Would love to continue playing the game on Epic.
Great tools btw.

**Comment by Z1ni** [comment]
If you could zip up the `%LOCALAPPDATA%\Packages\MattMakesGamesInc.Celeste_79daxvg0dq3v6\SystemAppData\wgs` folder and send it to me either here, by email or with Google Drive etc., I can take a look. You can find my email in my profile.

**Comment by Z1ni** [comment]
> has anyone done this yet or no? asking just in case i need to send

No. I'd appreciate if you could provide the files.

**Comment by TheKingOfShortness** [comment]
> > has anyone done this yet or no? asking just in case i need to send
> 
> No. I'd appreciate if you could provide the files.

sent the files via email

**Comment by Z1ni** [comment]
The [newest release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-10-08) now supports Celeste.
If you can try it out and confirm that it works, I'll then update the readme to say that it's tested.

**Comment by TheKingOfShortness** [comment]
> The [newest release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-10-08) now supports Celeste. If you can try it out and confirm that it works, I'll then update the readme to say that it's tested.

Celeste works well! Shows that everything I have collected has been collected, well for what I've seen so far, still need to sync Xbox and try it out

**Comment by TheKingOfShortness** [comment]
>> Celeste works well! Shows that everything I have collected has been collected, well for what I've seen so far, still need to sync Xbox and try it out

I was on steam version

**Comment by JimmyRespawn** [comment]
Just Cause 4 and Celeste
Confirm: PGP -> Epic works!!!
Thank you.
