### ISSUE TITLE
Being flagged by Windows Defender as Trojan:Script/Phonzy.B!ml

### ISSUE THREAD

**Issue by ebug64** [Z1ni/XGP-save-extractor#32]
Also, the **xgp-save-extractor.exe gets** turned into **$RL73JC8.exe** when being deleted and moved to Recycle Bin. Need an explanation please.

> ⚠️ NOTE: Some anti-virus/anti-malware software can flag the executable as malicious. The executable is produced with [PyInstaller](https://pyinstaller.org/) and contains the Python interpreter alongside with the same main.py script as in this repo.

I get that it may be flagged as malicious, but why is it being flagged as a Trojan specifically?

![Screenshot 2023-09-23 235256](https://github.com/Z1ni/XGP-save-extractor/assets/110210673/55ca7f55-268f-4dc7-80c4-b0533a76879a)
![Screenshot 2023-09-23 213748](https://github.com/Z1ni/XGP-save-extractor/assets/110210673/6e700353-5668-4384-8ecd-81e13796d115)

**Comment by Z1ni** [comment]
As Python is an interpreted scripting language, it needs an interpreter. PyInstaller includes this interpreter in the EXE and unzips it when run. See https://pyinstaller.org/en/stable/operating-mode.html#how-the-one-file-program-works.

Unfortunately, this is also pretty similar in operation as to what some malware/trojan programs do, which is why anti-virus programs sometimes deem the program malicious. See e.g. https://en.wikipedia.org/wiki/Dropper_(malware).

As to what's the `$RKTA3GX.exe` (etc.) file, maybe Windows Defender renames the executable when quarantining it or maybe that's a temporary executable from the PyInstaller bootstrap. :shrug:

**Comment by Z1ni** [comment]
One way to possibly solve the anti-virus false detections is to buy a code signing certificate and sign the executables with that. Unfortunately those certificates cost tens or usually hundreds of dollars, and the problem isn't so severe that I'd like to invest that amount of money to solve that.

I could also make an one-folder executable with PyInstaller (as opposed to an one-file executable), which should be nicer in the eyes of the anti-virus programs, but I think that the one-file solution is a lot easier for you, the users.

**Comment by CommandMC** [comment]
If you're willing to jump through some hoops, [SignPath](https://about.signpath.io/) offers a free [Open-Source Signing service](https://about.signpath.io/product/open-source)

**Comment by ebug64** [comment]
> As Python is an interpreted scripting language, it needs an interpreter. PyInstaller includes this interpreter in the EXE and unzips it when run. See https://pyinstaller.org/en/stable/operating-mode.html#how-the-one-file-program-works.
> 
> Unfortunately, this is also pretty similar in operation as to what some malware/trojan programs do, which is why anti-virus programs sometimes deem the program malicious. See e.g. https://en.wikipedia.org/wiki/Dropper_(malware).
> 
> As to what's the `$RKTA3GX.exe` (etc.) file, maybe Windows Defender renames the executable when quarantining it or maybe that's a temporary executable from the PyInstaller bootstrap. 🤷

I understand now. Thank you very much for taking the time to explain it, I really appreciate it ^^

**Comment by Z1ni** [comment]
> If you're willing to jump through some hoops, [SignPath](https://about.signpath.io/) offers a free [Open-Source Signing service](https://about.signpath.io/product/open-source)

Thanks for the link. I'll take a look sometime.
