### ISSUE TITLE
TABS support

### ISSUE THREAD

**Issue by Sambosis** [Z1ni/XGP-save-extractor#33]
Is it possible to add support for Totally Accurate Battle Simulator?  
Here is the zip of the directory I saw you request in a different issue. 

[LandfallGames.TotallyAccurateBattleSimulator_r2vq7k2y0v9ct.zip](https://github.com/Z1ni/XGP-save-extractor/files/12708977/LandfallGames.TotallyAccurateBattleSimulator_r2vq7k2y0v9ct.zip)

**Comment by Z1ni** [comment]
Sure, I'll take a look. Thanks for the files.

**Comment by Sambosis** [comment]
"TABS": "LandfallGames.TotallyAccurateBattleSimulator_r2vq7k2y0v9ct"
}

**Comment by Sambosis** [comment]
Sorry I hit send too soon, but it seems to follow this format with these
other games. but I'm not really sure
"TABS": "LandfallGames.TotallyAccurateBattleSimulator_r2vq7k2y0v9ct"
}


elif store_pkg_name in [supported_xgp_apps["Octopath Traveller"],
supported_xgp_apps["Just Cause 4"], supported_xgp_apps["Hades"],
supported_xgp_apps["TABS"]]:
        # Handle Octopath Traveller, Just Cause 4 and Hades saves
        # All of these games use containers in a "1 container, n files"
manner (1cnf), where there exists only one
        # container that contains all the savefiles.
        # The save files seem to be the same as in the Steam version.
        container = containers[0]
        for c_file in container["files"]:

**Comment by Z1ni** [comment]
Yeah, but the XGP save file name seems to be "TABSSave.TABSSAVE" instead of "TABSSAVE.TABSProgress", which is what I see in Steam saves downloaded from the internet.
I'm not sure if those saves are for an older version of the game, or if the game supports both, or if the XGP version expects that name and the Steam/Epic version expects the other one.

**Comment by Z1ni** [comment]
Here's your save file: [totally_accurate_battle_simulator_2535464150562459_2023-09-24_19_45_44.zip](https://github.com/Z1ni/XGP-save-extractor/files/12709171/totally_accurate_battle_simulator_2535464150562459_2023-09-24_19_45_44.zip)

If you could test that with the Steam version, so we can see if the game accepts the `TABSSave.TABSSAVE` file without needing to rename it to `TABSSAVE.TABSProgress`.

If that works, I'll add the support to the repository.

**Comment by Sambosis** [comment]
Thanks. It works as is without adding progress.

**Comment by Z1ni** [comment]
Great, committed the changes (41a870db8e939fd96fcc24d6a16a5fd51c9b074e) and [made a release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-09-26).
