### ISSUE TITLE
Missing Container?

### ISSUE THREAD

**Issue by Cubanbread** [Z1ni/XGP-save-extractor#35]
This is what I get when running the exe and main.py:

Xbox Game Pass for PC savefile extractor
========================================
Installed supported games:
- Starfield

  !! Missing container "Saves/Autosave1_CD65C61F_437562616E6272656164_020225_20230918222206_27_0_4.sfs" !!
     Xbox cloud save syncing might not be complete, try again later.
     Extracted saves for this game might be corrupted!
     Press enter to skip and continue.

**Comment by Z1ni** [comment]
The XGP save data can contain duplicate entries for same containers. Maybe the syncing is still in progress (I've seen some reports that the Xbox save syncing can take 30 minutes or more) or something else went wrong at some point, 🤷.

You can hit enter and the extracted saves will _most likely_ work and maybe even include the indicated file. In worst case, you might have missing savefiles in the export.

**Comment by Cubanbread** [comment]
Yea I figured it there might be an issue with sync. I left it open all night to see if it would finish, but no dice. I tried hitting enter, but it just keeps repeating the same message with no zip file output.

**Comment by Cubanbread** [comment]
Got it!!!
Just keep hitting enter until I get the output text.
Now I can finally downsize from 4 pet rocks lol.
Thank you for the amazing tool, this saved my playthrough.
