### ISSUE TITLE
Support for Wo Long

### ISSUE THREAD

**Issue by GreyThunder4** [Z1ni/XGP-save-extractor#36]

**Comment by Z1ni** [comment]
## From the issue template:


Game saves from the Xbox Game Pass / Microsoft Store version are needed to add support for the game.
Here's how to obtain the saves:
1. Open up the Windows Run dialog by pressing Win+R
2. Type in "%LOCALAPPDATA%\Packages" (without quotes)
3. Search for a folder name that possibly includes the name of the game or the name of the game developer or publisher. The name format should be something like "DeveloperOrPublisherName.PossibleGameName_RandomLettersAndNumbers", e.g. "BethesdaSoftworks.ProjectGold_3275kfvn8vcwc" for Starfield.

If you found a suitable folder name:
4. Copy and paste the folder name below in this text field. That's the package name for the game.
5. Open up the folder and the "SystemAppData" folder inside it.
6. Zip up the "wgs" folder.

If you didn't find any folder related to the game, check if the PCGamingWiki (https://www.pcgamingwiki.com/wiki/Home) has a page for the game.
If so, check under "Save game data location" -> "Windows / XGP / Microsoft Store" section in the game wiki page. The name format should be something like "DeveloperOrPublisherName.PossibleGameName_RandomLettersAndNumbers", e.g. "BethesdaSoftworks.ProjectGold_3275kfvn8vcwc" for Starfield.
If you still didn't find any save folder, make sure that the game is still installed. If you uninstall the game, the save files also get deleted and won't reappear in your computer until you install the game again.
You can always open this issue and include details about what you did and didn't find.


If you have the Steam / Epic version of the game installed, and have save files for it, please also include those in the zip. You can check the PCGamingWiki page for the save file location. This is not required, but it would save some time and it should make adding the game support faster.

**Comment by GreyThunder4** [comment]
Folder Name: 946B6A6E.WoLongFallenDynasty_dkffhzhmh6pmy
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/12777666/wgs.zip)
