### ISSUE TITLE
Support for Persona 5 Royal

### ISSUE THREAD

**Issue by Amerau** [Z1ni/XGP-save-extractor#41]
## Game package name: SEGAofAmericaInc.F0cb6b3aer_s751p9cej88mt

[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/12820634/wgs.zip)

**Comment by Z1ni** [comment]
The [newest release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-10-08) now supports Persona 5 Royal.
If you can try it out and confirm that it works, I'll then update the readme to say that it's tested.

**Comment by Amerau** [comment]
It worked perfectly for me :)
Thank you so much
