### ISSUE TITLE
Support for The Lamplighters League

### ISSUE THREAD

**Issue by GreyThunder4** [Z1ni/XGP-save-extractor#42]
## Game package name: ParadoxInteractive.ProjectWiseguy-PC_zfnrdv2de78ny
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/12826345/wgs.zip)

**Comment by Z1ni** [comment]
From the files it looks like that the saves are split to two (or more) folders, "Shared" and "Slot00". Each of the folders contain files like `page_something.dat` and `something.index`. Can you confirm this if you have the Steam saves available, as I didn't find any when searching the internet?

**Comment by GreyThunder4** [comment]
I do not have the Steam version, if I find some save I upload it

**Comment by GreyThunder4** [comment]
[Save.zip](https://github.com/Z1ni/XGP-save-extractor/files/12841300/Save.zip)

i found something

**Comment by Loxrie** [comment]
Set games.json to have:

        {
            "name": "The Lamplighters League",
            "package": "ParadoxInteractive.ProjectWiseguy-PC_zfnrdv2de78ny",
            "handler": "1cnf-folder"
        }

 Zip file contained:
 
     Shared
     Slot00
 
 In Slot00
 
     page_pElKF3sp4PvHwFJZ.dat
 
 Took that and renamed it:

     m_20250329_232033_Campaign1.hbssave
 
 used it to overwrite my Slot one campaign in steam.  This worked and the games show up and load.  Sadly didn't pop my achievements from the first mission though.
