### ISSUE TITLE
Support for Chained Echoes

### ISSUE THREAD

**Issue by GreyThunder4** [Z1ni/XGP-save-extractor#43]
## Game package name: DECK13.ChainedEchoesRelease_rn1dn9jh54zft
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/12826368/wgs.zip)

**Comment by GreyThunder4** [comment]
hello, I closed the thread because I managed to pass the saves simply by renaming the file

**Comment by Z1ni** [comment]
I'll still add support for this, so no need to close the issue.

**Comment by Z1ni** [comment]
The [newest release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-10-08) now supports Chained Echoes.
