### ISSUE TITLE
Support for Wo Long: Fallen Dynasty

### ISSUE THREAD

**Issue by GreyThunder4** [Z1ni/XGP-save-extractor#44]
## Game package name: 946B6A6E.WoLongFallenDynasty_dkffhzhmh6pmy
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/12826375/wgs.zip)

**Comment by Z1ni** [comment]
The [newest release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-10-08) now supports Wo Long: Fallen Dynasty.
If you can try it out and confirm that it works, I'll then update the readme to say that it's tested.

**Comment by jrodriguezml** [comment]
Hello, I recently tried it with wo long, but I get "the file is corrupted", could you please solve it?
<img width="909" alt="Captura de pantalla 2023-10-10 194913" src="https://github.com/Z1ni/XGP-save-extractor/assets/147563233/cb6bb197-c81c-420f-8d02-749e074992bc">

**Comment by jrodriguezml** [comment]
> The [newest release](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-10-08) now supports Wo Long: Fallen Dynasty. If you can try it out and confirm that it works, I'll then update the readme to say that it's tested.

Hello, I recently tried it with wo long, but I get "the file is corrupted", could you please solve it?
<img width="608" alt="image" src="https://github.com/Z1ni/XGP-save-extractor/assets/147563233/bdc4dca8-f93f-44f2-a630-93f27ccb302e">

**Comment by daedalus311** [comment]
The game says the save is for different player.
![image](https://github.com/Z1ni/XGP-save-extractor/assets/6960820/f206fe0c-c3b1-4ff7-a2a6-b8e8e84bb522)

**Comment by ShuraWrath** [comment]
> > A [versão mais recente](https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2023-10-08) agora suporta Wo Long: Fallen Dynasty. Se você puder testá-lo e confirmar que funciona, atualizarei o leia-me para informar que foi testado.
> 
> Olá, recentemente tentei por muito tempo, mas recebo "o arquivo está corrompido", você poderia resolver? <img alt="imagem" width="608" src="https://private-user-images.githubusercontent.com/147563233/274437685-bdc4dca8-f93f-44f2-a630-93f27ccb302e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NTk3MjMsIm5iZiI6MTcwMjc1OTQyMywicGF0aCI6Ii8xNDc1NjMyMzMvMjc0NDM3Njg1LWJkYzRkY2E4LWY5M2YtNDRmMi1hNjMwLTkzZjI3Y2NiMzAyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQyMDQzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmUzYTQ0NTE1MTZkYTlhOGMyOTMzMzUwODMxMzU3ZjUyZjlmOTVhNDQyNTlmNjVlYTMyMmNjYmExYTE1MjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8cUKl7MPdv9V9D1z8jVcEBEmyLni1JBdgQsWskQCUiw">

I'm having the same problem with corrupted files. Did anyone manage to solve it?

**Comment by revanmj** [comment]
I've found [this comment](https://www.reddit.com/r/wolongfallendynasty/comments/11hmnkj/comment/jaznxdi/) on Reddit, but trick from it unfortunately doesn't work for me (but to be honest, when I tried to load it in the Game Pass version, it crashes, so maybe it indeed got corrupted). 

There is also a [link to video](https://streamable.com/ecw0qs) showing more or less how to do this hex edit.

**Comment by Txkita** [comment]
Its not working at all. I made a lot of progress on game pass and I am struggling to get that save over to Steam. This is not working. does anyone have a fix because I am a little frustrated right now

**Comment by daedalus311** [comment]
> Its not working at all. I made a lot of progress on game pass and I am struggling to get that save over to Steam. This is not working. does anyone have a fix because I am a little frustrated right now

I ended up buying the DLC back around Christmas.
