### ISSUE TITLE
Add support for starfield

### ISSUE THREAD

**Issue by jjorstad2** [Z1ni/XGP-save-extractor#5]
if possible can you please add support for Starfield

**Comment by Z1ni** [comment]
I could look into it, but I only have the Steam version.

If you have the MS Store / Game Pass version and don't mind sharing your save with me, could you check `%LocalAppData%\Packages` and see if there's anything related to Starfield. If so, could you share the contents of `SystemAppData\wgs` inside the Starfield-related folder?

You can send me an email if you don't want to share the save file publicly.

**Comment by jjorstad2** [comment]
sure here you go
 wgs.7z
<https://drive.google.com/file/d/1mbs7ZjI6t6bMyKjGtLQlS1A3cP8tPxRW/view?usp=drive_web>

**Comment by Z1ni** [comment]
Can you please test the PR (if you also have the Steam version), as I didn't want to risk my current Starfield save 😄

**Comment by Z1ni** [comment]
Oh and the Steam version SFS save files live in `C:\Users\username\Documents\My Games\Starfield\Saves`

**Comment by jjorstad2** [comment]
The saves were out of order in game list but they loded just fine on the steam version of the game thank you

**Comment by Z1ni** [comment]
Great, thanks for testing!

**Comment by gjano** [comment]
Would it be possible to implement the other way around? I.e. converting Steam save into XGP

**Comment by Z1ni** [comment]
Maybe, but the WGS container index (the `containers.index` file) has some fields that I don't know the meaning of, so I don't really know how to reconstruct those. Maybe the information floats somewhere on the internet or maybe the values are not really used.

Either way it would require some extra research, which I might do some day. No promises here currently.

**Comment by gjano** [comment]
For other, simpler, games where 1 data file in WGS corresponds to 1 file in non-WGS I have just copied data from the non-WGS save into the containerized file (keeping the WGS header) and it worked (the save even works in XCloud then) so I guess at least `containers.index` does not contain checksums or even sizes (or it did not for those games). My guess is just being able to convert a SFS file into a container (i.e. a `container.2` file + bunch of _data_ files) should do it, then you'd just need to replace an existing container with the _exported_ one. However I am missing the logic to _split_ the original SFS file. Reconstructing is easier since you just need to append all of them in the right order but I have noticed they are not the same size so I guess there is a logic behind it. Maybe a container with a single data file would work... will try when I have the opportunity.

**Comment by gjano** [comment]
All "chunks" seem to begin with `78 5e`. I have checked my own non-WGS save and in fact if I search for aligned occurrences of `78 5e` most of the times they are preceded by some padding. However in some cases they are not, so it is unclear whether the previous block just randomly happened to have the _right_ size or the block is actually a false positive. I guess the size is stored somewhere in that block header but I couldn't figure it out yet (also not sure what size to look for, the full block, the block minus the header for which I don't know the length...)

**Comment by Z1ni** [comment]
The chunks are padded to the next 16-byte boundary with the repeating string `padding\0`, where `\0` is NUL.

**Comment by gjano** [comment]
I know, what I mean is if a block happens to have a size which is a exact multiple of 16 (so it does not need any padding) it is hard to tell if it is indeed a block or not. E.g. this one is the beginning of a block for sure:

![image](https://github.com/Z1ni/XGP-save-extractor/assets/7139171/f29b59a8-2253-49d3-ae31-bf82ecd7444c)

But this one could be a block or maybe a random `78 5e` just happened to be aligned:

![image](https://github.com/Z1ni/XGP-save-extractor/assets/7139171/75dd2307-d0e0-4291-bab2-ffa89ad96f41)

Like I said I guess somewhere after `78 5e` you have the size of the block (or part of it) so you could be 100% sure.

**Comment by gjano** [comment]
These 785E blocks are compressed using Zlib. So when a block fails to decompress, that means it's incomplete, so I append the next one. By doing this I think I have managed to convert a SFS file into a container. At least all the individual files except for the one corresponding to the beginning of the SFS file (BCPS header) can be decompressed using Zlib and they seem to contain meaningful information. Will try actually injecting them into the game when it launches on XGP.

**Comment by gnobre29** [comment]
Anyone test out Steam -> XGP save file conversion yet?

**Comment by gjano** [comment]
I can confirm the method I described above works for this purpose.

**Comment by ps3firebird** [comment]
@gjano  Can you explain how you were able to convert SFS to WGS.

**Comment by gnobre29** [comment]
Yes I have also been unable to understand how to do it only from the comments here... Sorry if it's a stupid question

**Comment by NSFLscott** [comment]
Yea, I'd love to be able to go from SFS to WGS as well!

**Comment by Juar99** [comment]
Same!

**Comment by Z1ni** [comment]
Tracking the Steam -> XGP conversion in #11, so I'm locking this issue.
Thanks @gjano for figuring out the details!
