### ISSUE TITLE
Support for Like a Dragon: Ishin!

### ISSUE THREAD

**Issue by GreyThunder4** [Z1ni/XGP-save-extractor#55]
## Game package name: SEGAofAmericaInc.ProjectMacan_s751p9cej88mt
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13059656/wgs.zip)

**Comment by Z1ni** [comment]
This is now supported in the latest release https://github.com/Z1ni/XGP-save-extractor/releases
