### ISSUE TITLE
Support for Middle-Earth: Shadow Of War

### ISSUE THREAD

**Issue by tizerheads** [Z1ni/XGP-save-extractor#64]
## Game package name: WarnerBros.Interactive.WB-Kraken_ktmk1xygcecda

WGS Zipped Gamesave Link: [https://1drv.ms/u/s!Ai6iR3p1I4UKlZYVLrN44ASlYn_j2w?e=bLtNiC]

**Comment by Luilem** [comment]
Hi! Any news about this?

**Comment by tizerheads** [comment]
None I’m afraid 😟

—This email was sent from my mobile device.—

**Comment by Z1ni** [comment]
Duplicate of #40
