### ISSUE TITLE
Support for [ Like a Dragon Gaiden: The Man Who Erased His Name]

### ISSUE THREAD

**Issue by SamBanz96** [Z1ni/XGP-save-extractor#66]
## Game package name: SEGAofAmericaInc.l1b05f489e_s751p9cej88mt

Xbox Save: 
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13466197/wgs.zip)

Steam Save:
[Steam.zip](https://github.com/Z1ni/XGP-save-extractor/files/13466206/Steam.zip)

**Comment by Z1ni** [comment]
This has now been released: https://github.com/Z1ni/XGP-save-extractor/releases

If you can confirm if the extracted save works, I'll update the readme to mark this as verified.

**Comment by SamBanz96** [comment]
Hello, very sorry for the long delay. Tried the update and it gave an error saying the save file is corrupted as shown. Was able to read that it was a completed save file though. Thank you very much for your time and effort. Really appreciate it.

![image_2024-04-09_224622457](https://github.com/Z1ni/XGP-save-extractor/assets/48748481/616212bc-7790-4028-aaac-5e9d169c892b)

**Comment by Z1ni** [comment]
Unfortunately the save formats seem to be a bit different (like in other Like a Dragon games), so I've marked this as unsupported. See #72 and #180.
