### ISSUE TITLE
Not working for starfield

### ISSUE THREAD

**Issue by GamingDaveUk** [Z1ni/XGP-save-extractor#7]
Moving from the game pass edition to the steam edition, currently both editions are installed.

cloned the repo

ran in both normal and elevated command window, same error:

`H:\>cd stuff

H:\stuff>cd XGP-save-extractor

H:\stuff\XGP-save-extractor>python main.py
Xbox Game Pass for PC savefile extractor
========================================
Installed supported games:
- Starfield
Traceback (most recent call last):
  File "H:\stuff\XGP-save-extractor\main.py", line 272, in <module>
    main()
  File "H:\stuff\XGP-save-extractor\main.py", line 251, in main
    save_paths = get_save_paths(store_pkg_name, containers, temp_dir)
  File "H:\stuff\XGP-save-extractor\main.py", line 208, in get_save_paths
    idx = int(file["name"].strip("P")) + 1
ValueError: invalid literal for int() with base 10: 'BlobData0'

H:\stuff\XGP-save-extractor>`

**Comment by GamingDaveUk** [comment]
If it helps, this is a copy of my WGS folder, I noticed you needed that to add support for starfield, maybe mine has a variation? https://drive.google.com/file/d/149nPkz4Vc8X83VbLjaIuuzf-8yBRBez1/view?usp=sharing

**Comment by Z1ni** [comment]
Your data contained files under `Settings/` path, which are now ignored. Interestingly my Steam save doesn't include any `Settings` folder under `C:\Users\username\Documents\My Games\Starfield`. I'll have to check the data and possibly add support for that in this script, but at least now the save conversion should work.

Thanks for reporting the issue and providing the files for testing!

**Comment by GamingDaveUk** [comment]
> 

Thank you for the super fast fix.
It now works fully!

If it was not for you, I would have lost 24 hours of game time, THANK YOU!
