### ISSUE TITLE
Support for Forza Horizon 4

### ISSUE THREAD

**Issue by AFEnMM** [Z1ni/XGP-save-extractor#71]

**Comment by Z1ni** [comment]
## From the issue template:


Game saves from the Xbox Game Pass / Microsoft Store version are needed to add support for the game.
Here's how to obtain the saves:
1. Open up the Windows Run dialog by pressing Win+R
2. Type in "%LOCALAPPDATA%\Packages" (without quotes)
3. Search for a folder name that possibly includes the name of the game or the name of the game developer or publisher. The name format should be something like "DeveloperOrPublisherName.PossibleGameName_RandomLettersAndNumbers", e.g. "BethesdaSoftworks.ProjectGold_3275kfvn8vcwc" for Starfield.

If you found a suitable folder name:
4. Copy and paste the folder name below in this text field. That's the package name for the game.
5. Open up the folder and the "SystemAppData" folder inside it.
6. Zip up the "wgs" folder.

If you didn't find any folder related to the game, check if the PCGamingWiki (https://www.pcgamingwiki.com/wiki/Home) has a page for the game.
If so, check under "Save game data location" -> "Windows / XGP / Microsoft Store" section in the game wiki page. The name format should be something like "DeveloperOrPublisherName.PossibleGameName_RandomLettersAndNumbers", e.g. "BethesdaSoftworks.ProjectGold_3275kfvn8vcwc" for Starfield.
If you still didn't find any save folder, make sure that the game is still installed. If you uninstall the game, the save files also get deleted and won't reappear in your computer until you install the game again.
You can always open this issue and include details about what you did and didn't find.


If you have the Steam / Epic version of the game installed, and have save files for it, please also include those in the zip. You can check the PCGamingWiki page for the save file location. This is not required, but it would save some time and it should make adding the game support faster.

**Comment by kisskisskaty** [comment]
ZIP :)
https://we.tl/t-4XB3q3phfm

**Comment by kisskisskaty** [comment]
sry, but same, game just crashing
![image](https://github.com/Z1ni/XGP-save-extractor/assets/16195972/9efeac9e-3366-4309-a96a-68d072f73631)

**Comment by Z1ni** [comment]
Shame :disappointed: 

I suppose then that the saves contain some account-specific stuff, which can't be transferred between different store versions (Microsoft/Steam).

I'll close this issue and won't add the support. It might also be that the Forza Horizon 5 saves can't be transferred, as the save format seems to be the same as in Horizon 4.

**Comment by AFEnMM** [comment]
Hello

Ok, thanks for your Time to try convert Save fh4.
Have a good Day :)
I try again with your instruction slowly maybe its work, but i think no

Regards
Piotr Lamont

śr., 24 sty 2024, 21:22 użytkownik Mark Mäkinen ***@***.***>
napisał:

**Comment by Z1ni** [comment]
>I try again with your instruction slowly maybe its work, but i think no

If you can zip up your wgs folder, I can convert the save for you to test.

**Comment by opa266** [comment]
Hello, could you try to convert my Forza 4 save? link to download the compressed wsg:
https://www.mediafire.com/file/mvunl1mha3sgv99/wgs.rar/file

**Comment by AFEnMM** [comment]
Hi.  I tried then, but nothing came of it.

niedz., 7 lip 2024, 00:41 użytkownik opa266 ***@***.***>
napisał:
