### ISSUE TITLE
Support for [Yakuza: Like A Dragon]

### ISSUE THREAD

**Issue by Will4759** [Z1ni/XGP-save-extractor#72]
## Game name: 
Yakuza: Like A Dragon

## Game package name: 
SEGAofAmericaInc.Yazawa_s751p9cej88mt
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13655216/wgs.zip)

**Comment by Z1ni** [comment]
The script has supported Yakuza: Like A Dragon since 2022-07-08.

Does it work for you?

**Comment by revanmj** [comment]
Save files from MS Store version are seen as corrupted by the Steam version. From what I've search around the web nobody knows how to make them work.

I created pull request with README.md update: https://github.com/Z1ni/XGP-save-extractor/pull/103

**Comment by Z1ni** [comment]
It seems that there's a checksum: https://github.com/SutandoTsukai181/yk2_save/releases/tag/YLaD_v1.0

**Comment by revanmj** [comment]
Yup, that app and manual from release notes (removing last bytes visible as strange symbols in VS Code with JSON opened before encrypting) worked!

Saves still did not show thumbnail or stats, but they loaded properly in Steam version and after saving them again, they now show up properly.
