### ISSUE TITLE
Support for [Railway Empire 2]

### ISSUE THREAD

**Issue by InclassAdam** [Z1ni/XGP-save-extractor#76]
## Game package name: KalypsoMediaGroup.RailwayEmpire2Win_e60j8nnj33ga6

[Railway Empire 2 wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13748437/Railway.Empire.2.wgs.zip)

**Comment by Z1ni** [comment]
The newest release now support this game. Please try it out and report back here if it works or not.
https://github.com/Z1ni/XGP-save-extractor/releases
