### ISSUE TITLE
Support for [State of Decay 2]

### ISSUE THREAD

**Issue by InclassAdam** [Z1ni/XGP-save-extractor#77]
## Game package name: Microsoft.Dayton_8wekyb3d8bbwe

[State of Decay 2 wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13748459/State.of.Decay.2.wgs.zip)

**Comment by Z1ni** [comment]
The newest release now support this game. Please try it out and report back here if it works or not.
https://github.com/Z1ni/XGP-save-extractor/releases
