### ISSUE TITLE
Support for [Death's Door]

### ISSUE THREAD

**Issue by Jan540** [Z1ni/XGP-save-extractor#79]
## Game package name: DevolverDigital.DeathsDoorWin10_6kzv4j18v0c96

[Death's Door wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13767319/Death.s.Door.wgs.zip)

**Comment by Z1ni** [comment]
Unfortunately the save files between the Game Pass and Steam versions look a bit different and have a somewhat different format, so I'm afraid that the saves can't be easily transferred.

Some technical details:
The saves are some serialized .NET classes (as the game is made with Unity), but with different class names between the store versions.
Also the Game Pass version seems to serialize the saves in one list whereas the Steam version serializes them in different files.

I'm marking this incompatible for now.
