### ISSUE TITLE
Can someone tell me where the saves Zip is?

### ISSUE THREAD

**Issue by Firefoxray** [Z1ni/XGP-save-extractor#8]
Can someone tell me where the hell the saves Zip is??? I have ran the tool about 20 times  but cant find the zips. Can someone point towards it for me?

**Comment by kristjan97** [comment]
https://github.com/Z1ni/XGP-save-extractor/blob/main/main.py#L265

**Comment by fr0573** [comment]
@FireFoxray, you will need to download the entire folder not just the main.py - then run the python script from inside that folder otherwise it will not create the zip.

**Comment by Z1ni** [comment]
The script saves the zip file(s) to the same directory you're running it in. It should display `Save files written to filename_here.zip` when it has created the zip. If it doesn't, maybe it prints out an error?

**Comment by fr0573** [comment]
I did the same thing I am assuming firefoxray did, im a n00b and just downloaded the main.py and not the entire repo.  When I ran just the main.py without the other files it did not create the zip.

**Comment by Z1ni** [comment]
It shouldn't need any other files to work, just the `main.py`. Are you running the script with `cmd` or are you just double-clicking it?

**Comment by fr0573** [comment]
This is what it looks like when i don't download and run the main.py from my downloads folder:
![just_main](https://github.com/Z1ni/XGP-save-extractor/assets/24837974/771243f9-00c5-477b-b21c-c063304d569d)

and this is what it looks like when i download the repo, unzip it to have the same folder structure as the repo:

![main](https://github.com/Z1ni/XGP-save-extractor/assets/24837974/a51dfedc-f2be-482e-8761-f3109bcd6dab)

**Comment by Firefoxray** [comment]
Hey guys, finally got it working thanks to everyone. Seems that my problem was not running it from the command prompt but instead just clicking main.py. Worked perfectly and now my new Steam Version works with my Xbox Version mods. Thanks again and sorry for the frustration, was just mad that I had to spend $100 for the Steam version just to mod.
