### ISSUE TITLE
Support for [Fuga melodies of steel 2] CyberConnect2Co.Ltd.FugaMelodiesofSteel2_zpv0gf6t8hz5r

### ISSUE THREAD

**Issue by Prakertyk** [Z1ni/XGP-save-extractor#82]
## Game name: Fuga melodies of steel 2

CyberConnect2Co.Ltd.FugaMelodiesofSteel2_zpv0gf6t8hz5r
## Game package name: CyberConnect2Co.Ltd.FugaMelodiesofSteel2_zpv0gf6t8hz5r

[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13804408/wgs.zip)

**Comment by Z1ni** [comment]
The newest release now support this game. Please try it out and report back here if it works or not.
https://github.com/Z1ni/XGP-save-extractor/releases
