### ISSUE TITLE
Support for Monster Train - Rougelike

### ISSUE THREAD

**Issue by Flaming-Phaser** [Z1ni/XGP-save-extractor#85]
## Game name:  Monster Train

[save-.zip](https://github.com/Z1ni/XGP-save-extractor/files/13945719/save-.zip)

## Game package name: 69C22BB6.MonsterTrain_8ekbzbj4dakee

 
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13945687/wgs.zip)

**Comment by Z1ni** [comment]
This has now been released https://github.com/Z1ni/XGP-save-extractor/releases.
Please test it and report back if it works.

**Comment by Flaming-Phaser** [comment]
didn't work, im seeing if i messed anything up

**Comment by Flaming-Phaser** [comment]
I got it, it works- i had two versions of the 'overall" save folder for steam, in two different hard drives. Just had to get rid of one.

**Comment by Flaming-Phaser** [comment]
THx
