### ISSUE TITLE
Support for Palworld

### ISSUE THREAD

**Issue by jjorstad2** [Z1ni/XGP-save-extractor#88]
## Game package name: PocketpairInc.Palworld_ad4psfrxyesvt

[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13987734/wgs.zip)
[SaveGames-Steam.zip](https://github.com/Z1ni/XGP-save-extractor/files/13988122/SaveGames-Steam.zip)

**Comment by TheDarkFleet** [comment]
Adding to this, containers are 1c1f and using that format outputs usable save files.

**Comment by VooDoo9** [comment]
> Adding to this, containers are 1c1f and using that format outputs usable save files. Files require .sav extension

So is there a way to already be able to use GP saves on Steam?

**Comment by Doct-Holiday** [comment]
I created a merge request, just waiting for them to approve, you can also pull my copy and run it yourself

**Comment by VooDoo9** [comment]
> I created a merge request, just waiting for them to approve, you can also pull my copy and run it yourself

Thank you 100% working!

**Comment by rktvr** [comment]
works as intended.
question regarding the game, how do I join my old world from gamepass as the character that was already on there?
when i join it asks me to make a new character. did i need to have steam running during converting or something?

**Comment by Z1ni** [comment]
The MR has now been released (thanks @Doct-Holiday), check https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2024-01-20 for the exe.
