### ISSUE TITLE
Support for Palworld

### ISSUE THREAD

**Issue by VooDoo9** [Z1ni/XGP-save-extractor#93]
## Game name: Palworld

[SaveGames.zip](https://github.com/Z1ni/XGP-save-extractor/files/13998584/SaveGames.zip)

## Game package name: PocketpairInc.Palworld_ad4psfrxyesvt

[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13998519/wgs.zip)

**Comment by Z1ni** [comment]
Duplicate of #88.
Palworld support has been added to the newest release, https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2024-01-20.
