### ISSUE TITLE
Support for [Hi-Fi RUSH]

### ISSUE THREAD

**Issue by BlucaWhale** [Z1ni/XGP-save-extractor#96]
## Game package name: BethesdaSoftworks.Hibiki_3275kfvn8vcwc

[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/14017895/wgs.zip)
https://drive.google.com/file/d/10VT_Q778h3OYRM2QdB96zTmk6PgVFcgU/view?usp=sharing

**Comment by Z1ni** [comment]
This has now been released: https://github.com/Z1ni/XGP-save-extractor/releases

If you can confirm if the extracted save works, I'll update the readme to mark this as verified.
